#!/bin/bash

# update all devhub-backend modules 
go get -u github.com/tigawanna/devhub-backend/...
go mod tidy

#  start docker for fly-io build
sudo systemctl start docker
# fly.io local build
fly deploy --local-only

#  build new exucutable nd commit push changes to github
./builder main.go

zip -r pocketbase.zip pocketbase.exe
git add .
git commit -m "updated version"
git push






